version: '3'

services:
  mongo_db:
    container_name: 'database'
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db

#  server:
#    container_name: server
#    build:
#      context: ./server
#      dockerfile: Dockerfile
#    ports:
#      - 3001:3001
#    environment:
#      PORT: 3001
#      MONGO_URI: mongodb://mongo_db:27017
#      DB_NAME: social-network
#      NAME: root
#    depends_on:
#      - mongo_db

volumes:
  mongo_db: {}